// examples/fhevm-vite-react/src/components/WalletButton.tsx
import { useAccount, useConnect, useDisconnect, useSwitchChain } from 'wagmi'
import { sepolia } from 'wagmi/chains'
import { useEffect, useState } from 'react'

export function WalletButton() {
  const { address, isConnected } = useAccount()
  const { connect, connectors } = useConnect()
  const { disconnect } = useDisconnect()
  const { switchChain } = useSwitchChain()
  const [actualChainId, setActualChainId] = useState<number | null>(null)

  // Get actual chainId from wallet
  useEffect(() => {
    const getChainId = async () => {
      if (isConnected && window.ethereum) {
        try {
          const chainId = await window.ethereum.request({ method: 'eth_chainId' })
          setActualChainId(parseInt(chainId, 16))
        } catch (error) {
          console.error('Failed to get chainId:', error)
        }
      }
    }

    getChainId()

    // Listen for chain changes
    if (window.ethereum) {
      const handleChainChanged = (chainId: string) => {
        setActualChainId(parseInt(chainId, 16))
      }
      window.ethereum.on('chainChanged', handleChainChanged)
      return () => {
        window.ethereum.removeListener('chainChanged', handleChainChanged)
      }
    }
  }, [isConnected])

  // Auto-switch to Sepolia when connected to wrong network
  useEffect(() => {
    if (isConnected && actualChainId && actualChainId !== sepolia.id) {
      switchChain({ chainId: sepolia.id })
    }
  }, [isConnected, actualChainId, switchChain])

  const isWrongNetwork = isConnected && actualChainId && actualChainId !== sepolia.id

  if (isConnected && address) {
    return (
      <div className="wallet-button">
        {isWrongNetwork && (
          <span className="warning">⚠️ Wrong Network</span>
        )}
        <span className="address">
          {address.slice(0, 6)}...{address.slice(-4)}
        </span>

        {isWrongNetwork ? (
          <button
            onClick={() => switchChain({ chainId: sepolia.id })}
            className="btn-primary"
          >
            Switch to Sepolia
          </button>
        ) : (
          <button onClick={() => disconnect()} className="btn-secondary">
            Disconnect
          </button>
        )}
      </div>
    )
  }

  return (
    <button
      onClick={() => connect({ connector: connectors[0] })}
      className="btn-primary"
    >
      Connect Wallet
    </button>
  )
}

// examples/fhevm-vite-vue/src/components/WalletButton.vue
<script setup lang="ts">
import { useAccount, useConnect, useDisconnect, useSwitchChain } from '@wagmi/vue'
import { sepolia } from 'viem/chains'
import { ref, computed, watch, onMounted, onUnmounted } from 'vue'

const { address, isConnected } = useAccount()
const { connect, connectors } = useConnect()
const { disconnect } = useDisconnect()
const { switchChain } = useSwitchChain()
const actualChainId = ref<number | null>(null)

// Get actual chainId from wallet
const getChainId = async () => {
  if (isConnected.value && (window as any).ethereum) {
    try {
      const chainId = await (window as any).ethereum.request({ method: 'eth_chainId' })
      actualChainId.value = parseInt(chainId, 16)
    } catch (error) {
      console.error('Failed to get chainId:', error)
    }
  }
}

// Listen for chain changes
const handleChainChanged = (chainId: string) => {
  actualChainId.value = parseInt(chainId, 16)
}

onMounted(() => {
  getChainId()

  if ((window as any).ethereum) {
    ;(window as any).ethereum.on('chainChanged', handleChainChanged)
  }
})

onUnmounted(() => {
  if ((window as any).ethereum) {
    ;(window as any).ethereum.removeListener('chainChanged', handleChainChanged)
  }
})

watch(isConnected, () => {
  getChainId()
})

// Auto-switch to Sepolia when connected to wrong network
watch([isConnected, actualChainId], () => {
  if (isConnected.value && actualChainId.value && actualChainId.value !== sepolia.id) {
    switchChain({ chainId: sepolia.id })
  }
})

const isWrongNetwork = computed(() =>
  isConnected.value && actualChainId.value && actualChainId.value !== sepolia.id
)

const handleConnect = () => {
  if (connectors.value && connectors.value[0]) {
    connect({ connector: connectors.value[0] })
  }
}
</script>

<template>
  <div v-if="isConnected && address" class="wallet-button">
    <span v-if="isWrongNetwork" class="warning">⚠️ Wrong Network</span>
    <span class="address">
      {{ address.slice(0, 6) }}...{{ address.slice(-4) }}
    </span>

    <button
      v-if="isWrongNetwork"
      @click="switchChain({ chainId: sepolia.id })"
      class="btn-primary"
    >
      Switch to Sepolia
    </button>
    <button v-else @click="disconnect()" class="btn-secondary">
      Disconnect
    </button>
  </div>

  <button v-else @click="handleConnect" class="btn-primary">
    Connect Wallet
  </button>
</template>
